# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 The SIG project. Code is Apache-2.0; data and documentation
# carry per-artifact licences — see LICENSE and docs/2_canonical_design_spec.md §42.
"""P34.40 / D-P34.13-1 — the dark serving-config machinery, offline layer.

`sig-ops web-conf` generates the conf/ fragments the sig-web nginx
glob-includes (branded 403/410 error_page wiring, the /task/ 403→404 map,
the /terms true-redirect); `sig-ops route-compare` is the byte-compare dark
check over the committed allow-list; `ops/Dockerfile`'s CMD conditionalises
`--release-registry` on the mount's presence; and the compose `serving`
profile wires edge/api/intake/web without disturbing `sig-ops up` (the
profile-free services are untouched).
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

import pytest
import yaml
from ops.route_compare import capture, route_paths, verify
from ops.web_conf import render_chrome_conf, render_terms_conf

REPO_ROOT = Path(__file__).resolve().parents[2]
NGINX_CONF = REPO_ROOT / "ops" / "web" / "nginx.conf"
OPS_DOCKERFILE = REPO_ROOT / "ops" / "Dockerfile"
COMPOSE = REPO_ROOT / "ops" / "docker-compose.yml"


# --- web-conf: the generated fragments ----------------------------------------


def test_chrome_fragment_wires_branded_errors_and_task_404() -> None:
    conf = render_chrome_conf()
    assert "error_page 403 /403.html;" in conf
    assert "error_page 410 /410.html;" in conf
    assert "location = /task/ { return 404; }" in conf
    # Generated bytes are deterministic — same call, same output.
    assert render_chrome_conf() == conf


def test_terms_fragment_is_a_real_302() -> None:
    conf = render_terms_conf("https://sig-api.example.run.app/")
    assert "location = /terms { return 302 https://sig-api.example.run.app/terms; }" in conf
    assert "location = /terms/ { return 302 https://sig-api.example.run.app/terms; }" in conf
    # Pure location blocks — no HTML/meta-refresh body anywhere.
    assert "<html" not in conf and "http-equiv" not in conf
    with pytest.raises(ValueError, match="absolute"):
        render_terms_conf("not-a-url")


def test_web_conf_cli_writes_chrome_and_guards_stale_terms(tmp_path: Path) -> None:
    def run(*extra: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            ["uv", "run", "--quiet", "sig-ops", "web-conf", "--out-dir", str(tmp_path), *extra],
            capture_output=True,
            text=True,
            check=False,
            cwd=str(REPO_ROOT),
        )

    proc = run("--api-base", "https://api.example/")
    assert proc.returncode == 0, proc.stderr
    assert (tmp_path / "chrome_routes.conf").read_text() == render_chrome_conf()
    assert (tmp_path / "terms_redirect.conf").exists()

    # Re-run WITHOUT --api-base refuses to silently leave a stale redirect.
    proc = run()
    assert proc.returncode == 4
    assert "stale" in proc.stderr
    (tmp_path / "terms_redirect.conf").unlink()
    proc = run()
    assert proc.returncode == 0
    assert not (tmp_path / "terms_redirect.conf").exists()


# --- route-compare: the byte-compare dark check --------------------------------


def _stub(responses: dict[str, tuple[int, bytes]]):
    def fetch(url: str) -> tuple[int, bytes]:
        return responses[url]

    return fetch


def test_route_compare_probe_set_covers_allowlist_and_denied() -> None:
    paths = route_paths()
    assert "/index.html" in paths and "/dossier/" in paths and "/task/" in paths
    # The denied routes are probed too — a deny flipping to served is a diff.
    for denied in ("/curate/", "/task/new/", "/intake/", "/visual-language/"):
        assert denied in paths
    assert paths == sorted(set(paths))


def test_route_compare_capture_and_verify_with_stub() -> None:
    # Build two captures from stubbed fetchers over a tiny allow-list file.
    import tempfile

    with tempfile.TemporaryDirectory() as d:
        al = Path(d) / "al.toml"
        al.write_text(
            '[allowlist]\ntop_level = ["index.html", "dossier"]\n'
            'required = ["index.html"]\n'
            '[[denied]]\npath = "/curate/"\nnote = "n"\n'
        )
        good = {
            "http://a/index.html": (200, b"home"),
            "http://a/dossier/": (200, b"dossier"),
            "http://a/curate/": (404, b""),
        }
        cap_a = capture("http://a", fetcher=_stub(good), allowlist_path=al)
        assert cap_a["schema"] == "route-capture/1"
        assert cap_a["routes"]["/dossier/"]["status"] == 200

        # Identical stub → clean verify.
        cap_b = capture(
            "http://b",
            fetcher=_stub({k.replace("http://a", "http://b"): v for k, v in good.items()}),
            allowlist_path=al,
        )
        assert verify(cap_a, cap_b) == []

        # Status drift + byte drift + a deny flipping to served are all diffs.
        drifted = dict(good)
        drifted["http://b/index.html"] = (500, b"home")
        drifted["http://b/dossier/"] = (200, b"dossier-changed")
        drifted["http://b/curate/"] = (200, b"leak")
        cap_c = capture(
            "http://b",
            fetcher=_stub({k.replace("http://a", "http://b"): v for k, v in drifted.items()}),
            allowlist_path=al,
        )
        diffs = verify(cap_a, cap_c)
        assert any("status 200 → 500" in d for d in diffs)
        assert any("body changed" in d for d in diffs)
        assert any("/curate/" in d and "404 → 200" in d for d in diffs)


def test_route_compare_dead_origin_is_an_error_not_a_deny() -> None:
    import tempfile

    def boom(url: str) -> tuple[int, bytes]:
        raise RuntimeError("origin unreachable")

    with tempfile.TemporaryDirectory() as d:
        al = Path(d) / "al.toml"
        al.write_text('[allowlist]\ntop_level = ["index.html"]\nrequired = ["index.html"]\n')
        with pytest.raises(RuntimeError, match="unreachable"):
            capture("http://dead", fetcher=boom, allowlist_path=al)


# --- nginx.conf: the fragment includes ------------------------------------------


def test_nginx_conf_carries_the_dark_fragment_includes() -> None:
    text = NGINX_CONF.read_text(encoding="utf-8")
    # The withdrawal + renamed barriers (pre-existing) and the two new globs,
    # all inside the server block and before the catch-all location.
    order = [
        "include /mnt/sig-web/conf/withdrawn_*.conf;",
        "include /mnt/sig-web/conf/renamed_*.conf;",
        "include /mnt/sig-web/conf/chrome_*.conf;",
        "include /mnt/sig-web/conf/terms_*.conf;",
        "location / {",
    ]
    pos = -1
    for needle in order:
        nxt = text.find(needle)
        assert nxt > pos, f"{needle} missing or out of order"
        pos = nxt
    # The branded 404 mapping is already wired; the chrome fragment owns
    # 403/410 (shipped dark — no live route change in this ticket).
    assert "error_page 404 /404.html;" in text
    # The P32.13 release locations and the barriers stay put.
    for loc in ("location /r/ {", "location /releases/ {", "location /entity/ {"):
        assert loc in text
    # No proxying: sig-web never forwards to a Cloud Run upstream (G3 §4.3 —
    # path rules live on the LB, not in this config).
    assert "proxy_pass" not in text
    # PMTiles are never in the compression type lists.
    for block in re.findall(r"(?:gzip_types|brotli_types)([^;]*);", text):
        assert "pmtiles" not in block


# --- ops/Dockerfile: the conditional registry flag ------------------------------


def test_api_image_cmd_conditionalises_release_registry() -> None:
    text = OPS_DOCKERFILE.read_text(encoding="utf-8")
    cmd = text.split("CMD ", 1)[1]
    assert "SIG_RELEASE_REGISTRY" in cmd
    assert "--release-registry" in cmd
    # The flag is conditional on the mount existing — absent dir ⇒ the serve
    # command is byte-identical to today's registry-less posture. (The CMD is
    # a JSON string, so the quotes are escaped in the file.)
    assert 'if [ -d \\"$REG\\" ]' in cmd
    # No Cloud SQL ⇒ demo store; the registry flag still applies.
    assert "sig-api serve --host" in cmd


def test_api_image_cmd_default_mount_path_matches_compose() -> None:
    text = OPS_DOCKERFILE.read_text(encoding="utf-8")
    assert "/mnt/rel/registry" in text
    compose = COMPOSE.read_text(encoding="utf-8")
    assert "/mnt/rel/registry:ro" in compose


# --- docker-compose: the serving profile ----------------------------------------


def test_serving_profile_shape() -> None:
    doc = yaml.safe_load(COMPOSE.read_text(encoding="utf-8"))
    services = doc["services"]

    # The serving profile services exist and are profile-gated — `sig-ops up`
    # (no profile) still starts only db + sqitch.
    for name in ("web", "api", "intake", "edge"):
        assert services[name]["profiles"] == ["serving"], name
    assert "profiles" not in services["db"]
    assert "profiles" not in services["sqitch"]

    # web: the real sig-web image over the staged site at the production path.
    web = services["web"]
    assert web["build"]["dockerfile"] == "ops/web/Dockerfile"
    (vol,) = web["volumes"]
    assert vol.endswith(":/mnt/sig-web:ro")

    # api: the real ops image with the registry mounted read-only at the path
    # its CMD conditionalises on.
    api = services["api"]
    assert api["build"]["dockerfile"] == "ops/Dockerfile"
    (vol,) = api["volumes"]
    assert vol.endswith(":/mnt/rel/registry:ro")

    # intake: mounted but NON-OPERATIONAL — SIG_INTAKE_ENABLED only; the
    # committed [intake].operational=false keeps it answering
    # 503 receiver_not_operating. No operational env is set here.
    intake = services["intake"]
    assert intake["environment"] == {"SIG_INTAKE_ENABLED": "1"}
    assert "serve-intake" in " ".join(intake["command"])

    # edge: stock nginx with the committed generated conf — published to
    # loopback only (the canonical-origin stand-in, never public).
    edge = services["edge"]
    assert edge["image"].startswith("nginx:")
    assert edge["volumes"] == ["./edge.conf:/etc/nginx/nginx.conf:ro"]
    (port,) = edge["ports"]
    assert port.startswith("127.0.0.1:")

    # Nothing world-reachable: every published port is loopback-bound.
    for name, svc in services.items():
        for p in svc.get("ports", []):
            spec = p if isinstance(p, str) else p.get("published", "")
            assert "127.0.0.1" in str(spec) or "${SIG_PG_PORT" in str(spec), (
                f"{name} publishes {spec} non-loopback"
            )
