// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The SIG project. Code is Apache-2.0; data and documentation
// carry per-artifact licences — see LICENSE and docs/2_canonical_design_spec.md §42.

/**
 * The static-PMTiles serving contract for the public map (SIG-UI-038, SIG-GEO-012/013).
 *
 * The public map MUST be served as **static PMTiles v3** generated by tippecanoe from
 * the resolution projection, a dynamic tile server MUST NOT be a hard dependency, and
 * the basemap MUST carry correct OpenStreetMap attribution in EVERY rendering context
 * including static exports and printed dossiers (a licence obligation, §42, not a
 * courtesy).
 *
 * This module is the single, testable source of truth for that contract. It exports a
 * MapLibre GL style object (ADR-018) whose sources are self-hosted, relative PMTiles v3
 * archives — no third-party tile CDN host anywhere — and the OSM attribution string the
 * page renders into its static HTML. The style is also served verbatim at
 * `/map/style.json` (see `pages/map/style.json.ts`), so "the map is served from static
 * PMTiles" is a real, fetchable artifact.
 *
 * Note (ADR reconciliation): the shell ships zero client JavaScript by default and the
 * Lighthouse budget forbids any script bytes (SIG-UI-036/037/041), so the maplibre-gl
 * *runtime* is not bundled into the archivable pages; the shipped `/map/` page is the
 * static SVG + tabular equivalent. What P15.3 lands is the serving CONTRACT above — the
 * style + self-hosted PMTiles source + attribution a MapLibre renderer consumes — which
 * is exactly what SIG-GEO-012/013 and SIG-UI-038 require of the *served map*.
 */

/** PMTiles archive version the public map is served as (SIG-GEO-012). */
export const PMTILES_VERSION = 3;

/**
 * The correct OpenStreetMap attribution, rendered in every context incl. print
 * (SIG-GEO-013). ODbL requires attributing OpenStreetMap and its contributors.
 */
export const OSM_ATTRIBUTION = "© OpenStreetMap contributors (ODbL)";

/** SIG's own attribution for the surveillance-infrastructure overlay. */
export const SIG_ATTRIBUTION = "Surveillance data © SIG contributors";

/** The self-hosted PMTiles archive paths (relative to the site origin, not a CDN). */
export const BASEMAP_PMTILES_URL = "/tiles/osm-basemap.pmtiles";
export const SIG_PMTILES_URL = "/tiles/sig-infrastructure.pmtiles";

/** The `pmtiles://` protocol prefix a MapLibre PMTiles source uses. */
export const PMTILES_PROTOCOL = "pmtiles://";

/**
 * A minimal, faithful subset of a MapLibre GL style. Only the fields the serving
 * contract constrains are typed here — the full spec is large and not our concern.
 */
export interface MapLibreVectorSource {
  type: "vector";
  /** A `pmtiles://<relative>` URL — self-hosted static PMTiles, never a tile server. */
  url: string;
  attribution: string;
}

export interface MapLibreStyle {
  version: 8;
  name: string;
  /** The declared PMTiles archive version this style consumes (SIG-GEO-012). */
  metadata: { "sig:pmtiles_version": number; "sig:serving": "static" };
  sources: Record<string, MapLibreVectorSource>;
  layers: Array<{ id: string; type: string; source: string; "source-layer"?: string }>;
}

/**
 * The public map's MapLibre GL style: an OSM basemap and the SIG infrastructure
 * overlay, both from self-hosted static PMTiles v3, each carrying its attribution.
 */
export const PUBLIC_MAP_STYLE: MapLibreStyle = {
  version: 8,
  name: "SIG public infrastructure map",
  metadata: { "sig:pmtiles_version": PMTILES_VERSION, "sig:serving": "static" },
  sources: {
    osm_basemap: {
      type: "vector",
      url: `${PMTILES_PROTOCOL}${BASEMAP_PMTILES_URL}`,
      attribution: OSM_ATTRIBUTION,
    },
    sig_infrastructure: {
      type: "vector",
      url: `${PMTILES_PROTOCOL}${SIG_PMTILES_URL}`,
      attribution: SIG_ATTRIBUTION,
    },
  },
  layers: [
    { id: "osm-basemap", type: "line", source: "osm_basemap", "source-layer": "roads" },
    { id: "sig-devices", type: "circle", source: "sig_infrastructure", "source-layer": "devices" },
  ],
};

/**
 * Host substrings that would make the public map depend on a third-party tile CDN —
 * exactly what SIG-UI-038/SIG-GEO-012 forbid as a hard dependency. Kept as a testable
 * denylist so a future edit that points a source at one of these fails the gate.
 */
export const THIRD_PARTY_TILE_HOSTS = [
  "mapbox",
  "maptiler",
  "stadiamaps",
  "stamen",
  "arcgis",
  "googleapis",
  "tile.openstreetmap.org",
  "basemaps.cartocdn",
  "protomaps.com",
];

function sourceUrlPath(url: string): string {
  return url.startsWith(PMTILES_PROTOCOL) ? url.slice(PMTILES_PROTOCOL.length) : url;
}

/** Whether a source url is a self-hosted, relative PMTiles path (no third-party CDN host). */
export function isSelfHostedTileUrl(url: string): boolean {
  const path = sourceUrlPath(url);
  // A self-hosted archive is a same-origin relative path: no scheme, no host.
  if (/^https?:\/\//i.test(path)) return false;
  if (!path.startsWith("/")) return false;
  const lower = path.toLowerCase();
  if (THIRD_PARTY_TILE_HOSTS.some((h) => lower.includes(h))) return false;
  return path.endsWith(".pmtiles");
}

/**
 * Assert the whole serving contract holds (SIG-UI-038, SIG-GEO-012/013): every source
 * is a self-hosted static PMTiles archive with no third-party tile CDN dependency, the
 * declared PMTiles version is v3, and OSM attribution is present. Throws otherwise.
 */
export function assertServingContract(style: MapLibreStyle = PUBLIC_MAP_STYLE): void {
  if (style.metadata["sig:pmtiles_version"] !== 3 || style.metadata["sig:serving"] !== "static") {
    throw new Error("SIG-GEO-012: the public map MUST be served as static PMTiles v3.");
  }
  const sources = Object.values(style.sources);
  if (sources.length === 0) throw new Error("SIG-GEO-012: the map style has no tile sources.");
  for (const src of sources) {
    if (!isSelfHostedTileUrl(src.url)) {
      throw new Error(
        `SIG-UI-038: map tile source ${src.url} is not a self-hosted static PMTiles archive ` +
          "(a third-party tile CDN MUST NOT be a hard dependency).",
      );
    }
  }
  const attributions = sources.map((s) => s.attribution).join(" ");
  if (!/openstreetmap/i.test(attributions)) {
    throw new Error("SIG-GEO-013: the basemap MUST carry OpenStreetMap attribution.");
  }
}

/** The attribution line rendered into the static HTML and print (SIG-GEO-013). */
export const MAP_ATTRIBUTION_LINE = `${OSM_ATTRIBUTION} · ${SIG_ATTRIBUTION}`;
