# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 The SIG project. Code is Apache-2.0; data and documentation
# carry per-artifact licences — see LICENSE and docs/2_canonical_design_spec.md §42.
"""P34.18 / ADR-178 — the renamed-identifier route barrier (SIG-PUB-002, B-3).

When a public identifier is renamed for personal-data protection, its old URL
must NOT 301 to the new page — that redirect would publish the old→new mapping
and repeat the handle. Instead every old route is an exact-match ``location =``
that serves the static N-5 page (``/sources/identifier-changed/``) directly:
same URL, neutral body, no handle anywhere in the response (A4, OD-19).

The generated ``conf/renamed_sources.conf`` lands next to ADR-132's
``withdrawn_*.conf`` barrier: the nginx ``location =`` exact matches are
evaluated before every prefix location, so an old identifier URL answers with
the N-5 page before any origin file access. The file lists OLD identifiers —
it is a serving-config artifact under ``conf/`` (a protected prefix), never a
published page, and it is generated from the restricted map by
``sig-ops renamed-routes`` so the handle list never has to be committed.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

#: The static page old identifier URLs serve (the committed N-5 notice).
NOTICE_BODY = "/sources/identifier-changed/index.html"

#: The public route shapes an old identifier can appear under. Old *source*
#: URLs are the retired surface; subject-id routes (dossier slugs) embed
#: source+target inside a longer id the conf cannot enumerate — those pages
#: are regenerated by P34.21b's republish #2 with neutral slugs. Kept narrow:
#: a ``location =`` that matches a still-live route would shadow it.
ROUTE_TEMPLATES: tuple[str, ...] = (
    "/sources/{id}",
    "/sources/{id}/",
)


def generate_conf(old_ids: list[str]) -> str:
    """Render the nginx exact-match barrier for every retired identifier."""
    lines = [
        "# P34.18 / ADR-178 — renamed-identifier barrier. Generated by",
        "# `sig-ops renamed-routes`; do not hand-edit. Old identifier URLs serve",
        "# the neutral N-5 page in place — never a redirect that would repeat",
        "# the handle or disclose the old->new mapping (DR-C6-01 / B-3).",
        "",
    ]
    for old in sorted(set(old_ids)):
        for template in ROUTE_TEMPLATES:
            route = template.format(id=old)
            lines.append(f"location = {route} {{ try_files {NOTICE_BODY} =404; }}")
        lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    """``sig-ops renamed-routes --out <staged>/conf/renamed_sources.conf``."""
    import argparse

    parser = argparse.ArgumentParser(prog="sig-ops renamed-routes")
    parser.add_argument(
        "--out",
        required=True,
        help="output path for the generated conf (e.g. <staged>/conf/renamed_sources.conf)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="print the rule count only; never prints identifiers",
    )
    args = parser.parse_args(argv)

    from policy.source_aliases import load_source_aliases

    aliases = load_source_aliases()
    old_ids = aliases.restricted_old_ids()
    if not old_ids:
        print("renamed-routes: no retired identifiers — nothing generated")
        return 0
    conf = generate_conf(old_ids)
    n_rules = conf.count("location = ")
    if args.dry_run:
        print(json.dumps({"retired_identifiers": len(old_ids), "rules": n_rules}))
        return 0
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(conf, encoding="utf-8")
    print(
        json.dumps(
            {
                "wrote": str(out),
                "retired_identifiers": len(old_ids),
                "rules": n_rules,
            }
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
