# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 The SIG project. Code is Apache-2.0; data and documentation
# carry per-artifact licences — see LICENSE and docs/2_canonical_design_spec.md §42.
"""D-P34.13-1 (P34.40) — the generated ``conf/`` fragments nginx wires dark.

``ops/web/nginx.conf`` includes ``/mnt/sig-web/conf/chrome_*.conf`` and
``/mnt/sig-web/conf/terms_*.conf`` — the same conf/-fragment mechanism the
withdrawal (``withdrawn_*.conf``) and renamed-identifier (``renamed_*.conf``)
barriers already use. Absent fragments are no-ops, so the P34.40 ``sig-web``
roll (L1) changes zero allow-listed responses; a fragment takes effect when
it lands under the bucket's ``conf/`` prefix (a publish-path write, owned
downstream of D-R10-PUBLISH-1) AND the running nginx reloads or rolls — the
include is read at start.

This module generates the two fragments deterministically:

* ``chrome_routes.conf`` — ``error_page 403``/``410`` onto the branded
  static assets (P34.13 ships ``/403.html`` + ``/410.html`` in the
  allow-listed build) and the ``/task/`` 403 → 404 map per G1's route table
  (the bare prefix is denied; ``/task/<handle>/`` stays allow-listed).
* ``terms_redirect.conf`` — a true 302 for ``/terms`` (and ``/terms/``) to
  the API's acceptable-use document — never a meta-refresh (WCAG 2.2.1,
  N-7). The API serves ``/terms`` at its own root (SIG-API-013), off the
  canonical origin's ``/v1/*`` rule, so the target is the API base URL the
  operator supplies (``SIG_API_BASE_URL``, the same value the web build
  bakes via ``publicApiBaseUrl()``).
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

#: The allow-listed branded pages (P34.13 — flat copies exist for exactly
#: this error_page mapping).
CHROME_ERROR_PAGES = {403: "/403.html", 410: "/410.html"}

#: The bare /task/ prefix is denied (G1 route table; the retired fixture
#: intake namespace under it stays refused by ops/public_routes.toml).
TASK_PREFIX_ROUTE = "/task/"


def render_chrome_conf() -> str:
    """``conf/chrome_routes.conf`` — branded error pages + /task/ → 404."""
    return (
        "# D-P34.13-1 / P34.40 — generated by `sig-ops web-conf`; do not\n"
        "# hand-edit. Lands under <bucket>/conf/ (a protected prefix).\n"
        "# Branded error pages (the assets ship in the allow-listed build):\n"
        + "".join(f"error_page {code} {page};\n" for code, page in CHROME_ERROR_PAGES.items())
        + "\n"
        "# G1 route table: the bare /task/ prefix is denied — answer a plain\n"
        "# 404 (branded via error_page 404 above in nginx.conf), never the\n"
        "# bucket's 403. /task/<handle>/ stays routed.\n"
        f"location = {TASK_PREFIX_ROUTE} {{ return 404; }}\n"
    )


def render_terms_conf(api_base: str) -> str:
    """``conf/terms_redirect.conf`` — a true 302 to the API terms document."""
    base = api_base.rstrip("/")
    if not base.startswith("http://") and not base.startswith("https://"):
        raise ValueError(f"--api-base must be an absolute http(s) URL, got {api_base!r}")
    return (
        "# D-P34.13-1 / P34.40 — generated by `sig-ops web-conf --api-base`;\n"
        "# do not hand-edit. A real 302 — never a meta-refresh that would\n"
        "# hide the N-7 notice or breach WCAG 2.2.1. The API's /terms lives\n"
        "# at its root (SIG-API-013), outside the canonical origin's /v1/*\n"
        "# rule, so the target is the API's own base URL.\n"
        f"location = /terms {{ return 302 {base}/terms; }}\n"
        f"location = /terms/ {{ return 302 {base}/terms; }}\n"
    )


def main(argv: list[str] | None = None) -> int:
    """``sig-ops web-conf --out-dir <staged>/conf [--api-base <url>]``."""
    parser = argparse.ArgumentParser(
        prog="sig-ops web-conf",
        description="D-P34.13-1 / P34.40: generate the dark conf/ fragments "
        "the sig-web nginx glob-includes — chrome_routes.conf (branded "
        "403/410 + /task/→404) always; terms_redirect.conf (/terms → the API "
        "terms, a real 302) only when an API base is supplied.",
    )
    parser.add_argument(
        "--out-dir",
        required=True,
        help="the staged tree's conf/ dir (e.g. <staged>/conf)",
    )
    parser.add_argument(
        "--api-base",
        default=os.environ.get("SIG_API_BASE_URL"),
        help="the read-API base URL the /terms redirect targets "
        "(default: $SIG_API_BASE_URL; unset ⇒ no terms fragment)",
    )
    args = parser.parse_args(argv)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    chrome = out_dir / "chrome_routes.conf"
    chrome.write_text(render_chrome_conf(), encoding="utf-8")
    written.append(str(chrome))
    if args.api_base:
        terms = out_dir / "terms_redirect.conf"
        terms.write_text(render_terms_conf(args.api_base), encoding="utf-8")
        written.append(str(terms))
    else:
        stale = out_dir / "terms_redirect.conf"
        if stale.exists():
            print(
                "web-conf: --api-base unset but a terms_redirect.conf exists — "
                "refusing to leave a stale redirect (remove it deliberately)",
                file=sys.stderr,
            )
            return 4
    print(json.dumps({"wrote": written}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
